[pytest]
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Маркировка для UI тестов
    regression: Маркировка для регрессионных тестов
    registration: Маркировка для тестов связанных с регистрацией
    smoke: Маркировка для смоук тестов.
    authorization: Маркировка для тестов связанных с авторизацией